version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:6000
  mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: ${MYSQL_INITIAL_PASSWORD:-initialpw}
      MYSQL_ONETIME_PASSWORD: "true"

volumes:
  mysql: